apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: eventstore-sample
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader